### ISSUE TITLE
TPCustomViews.txt gets overwritten every time I launch script

### ISSUE THREAD

**Issue by ghost** [RobTrew/tree-tools#10]
Doing edits directly in TPCustomViews.txt that way won't work... Any ideas? 

Update: Even adding and deleting via the script dialogue box only temporarily works, next time I run the the script, overwritten again...

**Comment by RobTrew** [comment]
Thanks ! 

I have amended the FileExists() function. 

This should work now.

**Comment by ghost** [comment]
A million thanx!

**Comment by RobTrew** [comment]
You are very welcome :-)

(and thanks for the report)
