### ISSUE TITLE
TaskPaperViews reappears after selecting view

### ISSUE THREAD

**Issue by ghost** [RobTrew/tree-tools#11]
Choosing view does closes the window but then it reappears, only hitting escape closes it.

**Comment by RobTrew** [comment]
Could you give me a sequence of actions to reproduce this ?

(If the dialog loses focus – i.e. you click elsewhere –  it may disappear behind another window, allowing you to unintentionally create a second instance.

**Comment by RobTrew** [comment]
I realise now that you are describing the main menu loop, which is by design (so that I can quickly try different views in succession).

If you are familiar with Applescript this could be amended by editing the main function.

**Comment by RobTrew** [comment]
I have now (ver .4) changed the default behaviour to what I understand to be your preference. 
i.e. it now quits as soon as a view is chosen or edited.
The behaviour can be reverted by editing pblnQuitOnViewSelect to False at the top of the script.

**Comment by ghost** [comment]
Thanx for changing default behavior, think this makes more sense!

Cheers!
