### ISSUE TITLE
AppleScript Error

### ISSUE THREAD

**Issue by sly-fox-git** [RobTrew/tree-tools#12]
FoldingText got an error: document "Untitled 2" doesn’t understand the “«event PTsuudtx»” message.

**Comment by RobTrew** [comment]
Is this a release version of FoldingText (ver 1) or a development version (ver 2) ?

FT2 (now in beta) uses a different script evaluation mechanism. I'll be adding FT2 scripts over the coming weeks, as I draft them for my own use.

**Comment by sly-fox-git** [comment]
I tried it with FT2. Will try with FT1.

Thanks.
