### ISSUE TITLE
/skimtoDevn errror

### ISSUE THREAD

**Issue by drsoram** [RobTrew/tree-tools#13]
Consistently get an error when running that says:

"Where is the GrowlHelperApp?" and the program does nothing 

yes DTP and Skim are both open ready to go --see attached photo

Thanks 
S

https://www.dropbox.com/s/eyhx2f47rz2u2do/Screenshot%202014-04-25%2022.13.24.png

**Comment by RobTrew** [comment]
Have a try with version 023.

If you don't have Growl on your system, you will need to comment out the lines which define a Growl notification function, and the line which calls that function.

**Comment by drsoram** [comment]
thanks Rob! I will get Growl and run 023!!

Best
Soram

**Comment by drsoram** [comment]
wow I just realized I must have Omni outliner also !
So this does not work without OmniOutliner?

thanks 
S

**Comment by RobTrew** [comment]
I wonder which script you are looking at now.

There is no involvement of or need for OmniOutliner in:

https://github.com/RobTrew/tree-tools/blob/master/DevonThink%20scripts/SkimToDevn-023.applescript

**Comment by drsoram** [comment]
thank you Rob
I must have gotten the wrong script ...Duh! sorry
I will review tonight after I get home from work

Thanks
Soram
