### ISSUE TITLE
Does not Compile

### ISSUE THREAD

**Issue by flodi** [RobTrew/tree-tools#14]
There are strange chars in the code in the import from OPML and the save as OPML for TaskPaper 3 that does not allow to compile or run the scripts.

Like:

set strOPMLFile to (POSIX path of �
            (choose file with prompt pTitle default location strSrcFolder))

or

if title of recOptions = "" then Â

**Comment by RobTrew** [comment]
The trick is probably to download the .zip of the [https://github.com/RobTrew/tree-tools](archive), and extract them from that (https://github.com/RobTrew/tree-tools/archive/master.zip)

(Applescript code can include some characters which are hard for Github to display in HTML)

**Comment by RobTrew** [comment]
(PS Using the .zip is best but I can see that the Applescript line continuation character doesn't display correctly (copiably) in GitHub HTML so I have now pruned it out of some of the scripts)
