### ISSUE TITLE
Script Error: fails looking for /Users/robintrew directory

### ISSUE THREAD

**Issue by jasonshanks** [RobTrew/tree-tools#3]
Hi - firstly, thanks so much for your efforts. I'm loving the expandable possibilities of FoldingText and you've gone far and beyond demonstrating this!

I did a search through the applescript and find no hardcoding of your user folder but somehow it goes looking for it when running this on a .todo fold.

**Scripting Error:**
`Error Number:FoldingText got an error: mkdir: /Users/robintrew: No such file or directory
1`

**Comment by RobTrew** [comment]
@plmtr thanks for the report. I wonder if that has got compiled into the .scpt version. Might be worth recompiling from the .applescript text version.  Which script are we talking about, incidentally ?

**Comment by jasonshanks** [comment]
sorry — Mark Done Time.scpt

and recompile fixed it thanks!

**Comment by RobTrew** [comment]
I'm glad to hear that. Thanks for telling me.
