### ISSUE TITLE
OmniFocus2DayOne - Logging Files not in Home Dir

### ISSUE THREAD

**Issue by joshuacole** [RobTrew/tree-tools#4]
Is there a way to put the logging files in a directory that is not $HOME?

I tried writing in $HOME/Dropbox/Application Support/DayOne/Logs and it failed to make any files other than DoneToday.txt

Thanks

**Comment by RobTrew** [comment]
Outside descendants of your home directory you probably won't automatically have write permissions, but as long as you set the permissions correctly you should be able to write files anywhere.
